language: python

python:
  - 3.6


install:
  - pip install coveralls

script:
  - pip install -r requirements.txt
  - coverage run --source=bind_json_error_handlers setup.py test
  - coverage report -m

after_success:
  - coveralls
